security:
    encoders:
        SportBundle\Entity\User:
            algorithm: plaintext

    providers:
        db_provider:
            entity:
                class: SportBundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/(en|ru)/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|ru)/exercises, roles: ROLE_USER }